server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schedule?useSSL=false
    username: root
    password: hyf5201314
    driver-class-name: com.mysql.cj.jdbc.Driver
#  shardingsphere:
#    sharding:
#      default-database-strategy:
#      tables:
#      discovery:
#        cluster-name: HZ
mybatis-plus:
  type-aliases-package: staff.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
pattern:
  name: 本地环境local