logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: 39.105.228.223 # rabbitMQ的所在主机地址
    port: 5672 # 数据交换端口
    username: admin # 用户名
    password: 123456 # 密码
    virtual-host: / # 虚拟主机
    listener:
      simple:
        prefetch: 1