logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
server:
  port: 8812
spring:
  rabbitmq:
    host: 116.204.64.181 # rabbitMQ的所在主机地址
    port: 5672 # 数据交换端口
    username: admin # 用户名
    password: 123456 # 密码
    virtual-host: / # 虚拟主机
    listener:
      simple:
        prefetch: 1
  application:
    name: rabbitMQConsumer
  cloud:
    nacos:
      server-addr: 8.130.69.82:8848 # nacos地址
