spring:
  cloud:
    sentinel:
      transport:
        dashboard: 8.130.69.82:8858 # Sentinel Dashboard的地址
    nacos:
      discovery:
        server-addr: 8.130.69.82:8848 # nacos地址
  application:
    name: sentinel-server # sentinel服务名
server:
  port: 8856


